CuBoulder/ucb_site_configuration

config/install/ucb_site_configuration.configuration.yml
src/SiteConfiguration.php

This update adds secondary and footer menus in the header and footer of the site. Like with the main navigation, links can be added when creating or editing a page. The secondary menu can be displayed either to the right of or above the main navigation, with the option to display action links as buttons.
CuBoulder/tiamat-theme#163
Sister PRs in:
- [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/22)
- [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/29)
- [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/187)

Adds secondary and footer menus

---

config/install/ucb_site_configuration.configuration.yml
css/admin-helpscout-beacon.css
js/admin-helpscout-beacon.js
src/Controller/HelpController.php
ucb_site_configuration.info.yml
ucb_site_configuration.install
ucb_site_configuration.libraries.yml
ucb_site_configuration.module
ucb_site_configuration.routing.yml

This update integrates Helpscout Beacon into the admin toolbar "Help" item for both normal and administration pages, providing quick access to help topics or to ask a question. It also redirects the default Drupal help pages to more relevant help documentation at https://websupport.colorado.edu/.
Resolves CuBoulder/tiamat-theme#170

Admin toolbar Helpscout Beacon integration

---

config/install/ucb_site_configuration.configuration.yml
config/install/ucb_site_configuration.settings.yml
src/Form/AppearanceForm.php
src/Form/GeneralForm.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml
ucb_site_configuration.install
ucb_site_configuration.links.menu.yml
ucb_site_configuration.links.task.yml
ucb_site_configuration.module
ucb_site_configuration.permissions.yml
ucb_site_configuration.routing.yml

This update to CU Boulder Site Configuration introduces a new "General" configuration form accessible for users with the "Edit the site general settings" permission. The form allows editing of site information:
- Site name
- Site type (optional, selected from a list of presets)
- Site affiliation (optional, selected from a list of presets or custom defined)
The site affiliation is always displayed underneath the site name in the header of the site.
CuBoulder/tiamat-theme#210
CuBoulder/tiamat-theme#211
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/215)

Adds site type, site affiliation

---

src/Controller/SiteSettingsMenuController.php
ucb_site_configuration.info.yml
ucb_site_configuration.routing.yml

This update includes these changes across several repos:
- Hides inaccessible items from the Admin Toolbar by installing Admin Toolbar Links Access Filter
- Hides inaccessible items from "Add content" and "CU Boulder site settings"
CuBoulder/tiamat-theme#240; Author @TeddyBearX
Sister PRs in: [ucb_admin_menus](https://github.com/CuBoulder/ucb_admin_menus/pull/6), [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/32)

Hides administration items that a user doesn't have access to

---

config/install/ucb_site_configuration.configuration.yml
config/install/ucb_site_configuration.contact_info.yml
src/Form/AppearanceForm.php
src/Form/ContactInfoForm.php
src/Plugin/Block/SiteInfoBlock.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml
ucb_site_configuration.install
ucb_site_configuration.permissions.yml
ucb_site_configuration.services.yml

This update:
- Adds an _Advanced_ view at the bottom of the _Appearance_ settings, collapsed by default and visible only to those with the _Edit advanced site settings_ permission.
- Moves all theme settings previously restricted to Drupal's default theme settings into the _Advanced_ view.
- Adds site-specific custom logos (CuBoulder/tiamat-theme#264) and places the settings for custom logos into the _Advanced_ view:
- Custom logo requires _white text on dark header_ and _dark text on white header_ variants.
- An image can be uploaded or a path can be manually specified for each.
- ~~A scale can be specified, which defaults to _2x_ (Retina) but also allows _1x_ (standard) or _3x_ (enhanced Retina)~~.
- Assigns the _Architect_ and _Developer_ user roles the _Edit advanced site settings_ …

Adds "Advanced" appearance settings and custom site logos; modifies contact info settings

---

src/SiteConfiguration.php

This update adds an optional "sticky menu" component to all pages on a site, enabled by visiting CU Boulder site settings → Appearance and toggling on _Show sticky menu_. The menu appears automatically when a user scrolls down passed the main website header, and only on large screen devices (at least 960 pixels wide).
CuBoulder/tiamat-theme#247
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/271)

Adds sticky menu

---

config/install/ucb_site_configuration.settings.yml
src/Form/ExternalServiceIncludeEntityForm.php
src/Form/GeneralForm.php
src/Form/RelatedArticlesForm.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml
ucb_site_configuration.links.menu.yml
ucb_site_configuration.links.task.yml
ucb_site_configuration.module
ucb_site_configuration.permissions.yml
ucb_site_configuration.routing.yml

This update adds a "Related articles" configuration form to CU Boulder Site Settings, accessible via the menu or `/admin/config/cu-boulder/related-articles`. Here users with permission can exclude articles with specific categories or tags from appearing in "related articles" sections. Resolves CuBoulder/ucb_site_configuration#22
This update also fixes a bug which caused warnings to appear when configuring a third-party service. Resolves CuBoulder/ucb_site_configuration#21
Sister PR in: [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/47), [tiamat10-profile](https://github.com/CuBoulder/tiamat10-profile/pull/7)

Adds a global "Related articles" configuration form to CU Boulder Site Settings

---

src/SiteConfiguration.php

CU Boulder Site Settings → Appearance features a new "Menu style" menu. Resolves CuBoulder/ucb_site_configuration#24.
Sister issue as: CuBoulder/tiamat-theme#330 (PR [here](https://github.com/CuBoulder/tiamat-theme/pull/416))

Adds "Menu style" setting to Appearance

---

src/SiteConfiguration.php

CuBoulder/tiamat-theme#435
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/452), [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/70), [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/52), [tiamat10-profile](https://github.com/CuBoulder/tiamat10-profile/pull/13), [tiamat-project-template](https://github.com/CuBoulder/tiamat-project-template/pull/28), [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/8)

Removes "D9" from theme name and the theme, custom entities Composer package names

---

src/Controller/ExternalServiceIncludeListBuilder.php
src/Controller/SiteSettingsAccessController.php
src/Controller/SiteSettingsMenuController.php
src/Entity/ExternalServiceInclude.php
src/Entity/ExternalServiceIncludeInterface.php
src/Form/AppearanceForm.php
src/Form/ContactInfoForm.php
src/Form/ExternalServiceIncludeEntityDeleteForm.php
src/Form/ExternalServiceIncludeEntityForm.php
src/Form/GeneralForm.php
src/Form/RelatedArticlesForm.php
src/Plugin/Block/SiteInfoBlock.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml
ucb_site_configuration.install
ucb_site_configuration.module
ucb_site_configuration.permissions.yml
ucb_site_configuration.routing.yml

This update to CU Boulder Site Configuration:
- Adds a new home page setting to CU Boulder site settings. Resolves CuBoulder/tiamat-theme#506
- Adds a new `edit ucb site pages` permission:
- Architect, Developer, and Site Manager have been given this new permission. 
- While "Pages" could eventually be split off into its own tab, the settings are found under "General", at least for now. The existing settings in "General" still require `edit ucb site general` to access.
- Cleans up PHP files in CU Boulder Site Configuration according to Drupal coding standards. Full compliance has not yet been achieved. CuBoulder/ucb_site_configuration#27
Sister PR in: [tiamat10-profile](https://github.com/CuBoulder/tiamat10-profile/pull/30)

Adds home page setting to CU Boulder site settings

---

src/Form/AppearanceForm.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml
ucb_site_configuration.module

This update:
- Moves campus alerts setting into "Advanced". Resolves CuBoulder/ucb_site_configuration#31
- Sets the weight of "Third-party services" in node sidebars to 35, placing it below "URL alias". Resolves CuBoulder/ucb_site_configuration#30

CU Boulder site configuration 2.5.1

---

src/SiteConfiguration.php

Changes the People List `Filter 1`, `Filter 2`, and `Filter 3` custom labels to a Global Setting in Site Configuration, rather than being set per-page. These labels will be set under Configuration => Cu Boulder Site Settings => Appearance and Layout.
Resolves [#543 ](https://github.com/CuBoulder/tiamat-theme/issues/543)
Includes:
- `ucb_site_configuarion` => https://github.com/CuBoulder/ucb_site_configuration/pull/35
-  `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/560
-  `ucb_custom_entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/87

People List Filter Labels as a Global Setting

---

src/SiteConfiguration.php
ucb_site_configuration.info.yml

This update:
- Reorganizes the _Appearance and layout_ section of CU Boulder site settings into three categories: _Header and navigation_, _Page content_, and _Miscellaneous_.
- Adds a _Heading font_ setting. The setting defaults to _Bold_ but can also be set to _Normal_. CuBoulder/tiamat-theme#516.
- Swaps the location of _Inline_ and _Above_ when choosing the secondary menu position. CuBoulder/tiamat-theme#551
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/578)

CU Boulder Site Configuration v2.6.1

---

src/SiteConfiguration.php
ucb_site_configuration.info.yml

This update changes "Display links in the secondary menu as buttons" to "Secondary menu button display" with options for none, blue, gold, and gray. The setting only appears if "Position of the secondary menu" is set to "Above the main navigation". CuBoulder/tiamat-theme#551
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/583)

CU Boulder Site Configuration v2.6.2

---

config/install/ucb_site_configuration.settings.yml
src/Form/ContentTypesForm.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml

CuBoulder/tiamat-theme#626
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/636)

Adds label fields for "Department" and "Job Type" on People List Pages

---

src/Form/AppearanceForm.php
src/SiteConfiguration.php
ucb_site_configuration.info.yml

This update:
- Fixes an error in Drupal 10.2 caused by a dependency on a `ThemeSettingsForm` class marked as internal. This dependency has been removed. Resolves CuBoulder/ucb_site_configuration#43
- Moves "Sidebar position" under Advanced in Appearance and layout, with the setting now expecting a value of either `left` or `right`. Updates are needed in the theme and profile to make the setting work and will be tagged as sister PRs, but aren't required to merge this PR. CuBoulder/tiamat-theme#633.
@jnicholCU assigned as the reviewer to test the primary fix of this update.

CU Boulder Site Configuration v2.6.4

---

src/SiteConfiguration.php
ucb_site_configuration.info.yml

Apparently Drupal's query API is so limiting that they actively encourage [duplicating the exact same code 3 times](https://www.drupal.org/docs/8/api/database-api/dynamic-queries/conditions#s-using-not-in-with-multi-value-field-like-roles-user-entity) in the documentation, big yikes. Instead of a query condition this update just grabs all of them and uses PHP to filter some out.
Resolves CuBoulder/ucb_site_configuration#51

Fixes third-party services set to "all content" appearing on content in the exclude field (v2.8.1)

---

src/SiteConfiguration.php

Previously there was an error in the site configuration where the set Filter 1 label would be presented for Filter 2 and Filter 3. This has been corrected and allows the People List Page to access the correct term labels.
Resolves #60

Fixes People List Filter labels

---

src/SiteConfiguration.php

Options for sidebar menu styles added. Default is the current D10 Gold, and the light gray option mimics the D7 style
Sister PR: https://github.com/CuBoulder/tiamat-theme/pull/1544

Adds Sidebar color options

---

config/install/ucb_site_configuration.configuration.yml
ucb_site_configuration.info.yml
ucb_site_configuration.install

This update renames _Office of Integrity, Safety and Compliance_ to _Office of Compliance, Ethics and Policy_, and adds a URL to this affiliation.
[change] Resolves CuBoulder/ucb_site_configuration#74

Updates site affiliation (v2.10)

---

src/SiteConfiguration.php
ucb_site_configuration.info.yml

This update removes the unused includes and settings originally intended for the CU Boulder homepage secondary and footer menus. They have instead built these out using the appropriate mechanisms available in Web Express and don't need custom code to support it.
CuBoulder/tiamat-theme#1537
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/1554)

Removes unused include templates and settings (v2.11)

---

ucb_site_configuration.install

Previously disabling the "Newsletters by Type" view would continue to cannibalize the "Taxonomy Terms" view page and result in a blank page due to both views sharing a path by default. This could only be disabled by changing the path, then disabiling the view on live sites, in order to correctly render the taxonomy view.
This update hook should disable the newsletter-specific view and allow the taxonomy view to handle all terms correctly, after running a `drush updb` command on the live sites
Resolves #78

#78 Adds update to remove newsletter view

---

config/install/ucb_site_configuration.configuration.yml
js/service-goodkind.js
src/Form/ExternalServiceIncludeEntityForm.php
ucb_site_configuration.install
ucb_site_configuration.libraries.yml

Adds the Goodkind AI chatbot to External Services. Cannot test locally, gets a 500 error. Need to test on developer sandbox.
Resolves #80

#80 Adds Goodkind bot to external service

---

js/service-goodkind.js

Needed to push the Goodkind chat bot to sandboxes for testing as it only works on a specified public domain. Included debug logging in case of issues, but this is no longer needed.
Resolves #82

Remove debug logging from Goodkind bot

---

config/install/ucb_site_configuration.configuration.yml
ucb_site_configuration.info.yml
ucb_site_configuration.install

This update renames 'Division of Student Affairs' to 'Division of Student Life', via an update hook. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1629

Renames Division of Student Affairs to Division of Student Life (v2.11)

---

src/Form/ExternalServiceIncludeEntityForm.php

When Salesforce Enhanced Chat third-party service was added to Third Party Services, the form fields were set as strictly `Required` which would cause other third-party services to need these fields even if you were not adding the Salesforce chat client. 
This has been corrected so they are only required if the Salesforce Enhanced Chat is selected.
Resolves #92

#92 - Fixes required Salesforce Enhanced form fields
